# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  { on = [
    "/",
    "s",
  ], run = "plugin what-size", desc = "Calc size of selection or cwd" },
  { on = [
    "/",
    "c",
  ], run = "plugin what-size -- clipboard", desc = "Calc size of selection or cwd" },
  { on = [
    "/",
    "h",
  ], run = "hidden toggle", desc = "Toggle hidden" },
  { on = "2", run = "plugin smart-switch 1", desc = "Switch or create tab 2" },
  { on = "t", run = "plugin smart-tab", desc = "Create a tab and enter the hovered directory" },
  { on = "p", run = "plugin smart-paste", desc = "Paste into the hovered directory or CWD" },
  { on = "!", run = 'shell "$SHELL" --block', desc = "Open shell here" },
  { on = [
    "m",
    "a",
  ], run = "plugin archivemount --args=mount", desc = "Mount selected archive" },
  { on = [
    "m",
    "u",
  ], run = "plugin archivemount --args=unmount", desc = "Unmount and save changes to original archive" },
  { on = [
    "g",
    "i",
  ], run = "plugin lazygit", desc = "run lazygit" },
  { on = [
    "C",
  ], run = "plugin ouch 7z", desc = "Compress with ouch" },
]
