#!/bin/bash

# Exit on any error
set -e

# Check if we have at least 2 arguments
if [ "$#" -lt 2 ]; then
  echo "Usage: $0 source_directory destination_directory"
  exit 1
fi

# Ensure destination directory exists
if [ -e "$2" ]; then
  rm -rf "$2"
fi
mkdir -p "$2"

# Perform rsync with error handling
if ! rsync -armR --info=progress2 \
  --exclude='.esbuild' \
  --exclude='.jest' \
  --exclude='.history' \
  --exclude='.pnpm-store' \
  --exclude='node_modules/' \
  --exclude='.tmp/' \
  --exclude='.git/' \
  --exclude='.webpack/' \
  --exclude='.serverless/' \
  --exclude='coverage/' \
  --delete \
  --checksum \
  --stats \
  --human-readable \
  "$@"; then
  echo "Error: rsync failed"
  exit 1
fi