#!/usr/bin/env bash

# https://starship.rs
# https://starship.rs/guide/#🚀-installation
# cross-shell prompt
# Fixed: __configure -> __reconfigure (typo in original)

function setup_util_starship() (
	source "$DOROTHY/sources/bash.bash"

	# options
	local option_reconfigure='yes'
	__flag --target={option_reconfigure} --name='reconfigure' --affirmative --coerce -- "$@"

	# helpers
	function __reconfigure {
		# if reconfigure is not desired, then don't reconfigure
		if [[ $option_reconfigure == 'no' ]]; then
			return 0
		fi

		# if starship, note fonts
		if __command_exists -- starship; then
			__print_style \
				'If you see unknown icons while using Starship, you probably require fonts:' --newline \
				--code='setup-util-noto-emoji # for emojis' --newline \
				--code='setup-util-nerd-fonts # for glyphs' --newline \
				'Then set your terminal to use one of the installed fonts.' || return
		fi

		# reconfigure nushell regardless of starship existence
		if __command_exists -- nu; then
			setup-util-nu --configure --quiet || return
		fi
	}

	# improve performance for detectable utilities with conditional assets
	if setup-util --check --cli=starship "$@"; then
		__reconfigure || return
		return 0
	fi

	# don't interfere with github download:
	# INSTALLER='https://starship.rs/install.sh'
	local arch options=(
		--name='Starship'
		--cli='starship'
		"$@"
		PACMAN='starship'            # ARCH (extra repo)
		BREW='starship'
		SCOOP='starship'
	)
	function __get_github_asset_url {
		local regexp
		regexp="$(echo-escape-regexp -- "$1")$" || return
		github-download --dry --slug='starship/starship' --latest --asset-regexp="$regexp" | echo-first-line || return
	}
	function __add_download_option {
		local suffix="$1" glob="$2" url
		url="$(__get_github_asset_url "$suffix")" || return
		options+=(
			DOWNLOAD="$url"
			DOWNLOAD_ARCHIVE_GLOB="$glob"
		)
	}
	arch="$(get-arch)" || return
	if is-mac; then
		if [[ $arch == 'a64' ]]; then
			__add_download_option '-aarch64-apple-darwin.tar.gz' 'starship' || return
		elif [[ $arch == 'x64' ]]; then
			__add_download_option '-x86_64-apple-darwin.tar.gz' 'starship' || return
		fi
	elif is-linux; then
		if [[ $arch == 'a64' ]]; then
			__add_download_option '-aarch64-unknown-linux-musl.tar.gz' 'starship' || return
		elif [[ $arch == 'a32' ]]; then
			__add_download_option '-arm-unknown-linux-musl.tar.gz' 'starship' || return
		elif [[ $arch == 'x64' ]]; then
			__add_download_option '-x86_64-unknown-linux-musl.tar.gz' 'starship' || return
		elif [[ $arch == 'x32' ]]; then
			__add_download_option '-i686-unknown-linux-musl.tar.gz' 'starship' || return
		fi
	elif is-windows; then
		if [[ $arch == 'a64' ]]; then
			__add_download_option '-aarch64-pc-windows-msvc.zip' 'starship.exe' || return
		elif [[ $arch == 'x64' ]]; then
			__add_download_option '-x86_64-pc-windows-msvc.zip' 'starship.exe' || return
		elif [[ $arch == 'x32' ]]; then
			__add_download_option '-i686-pc-windows-msvc.zip' 'starship.exe' || return
		fi
	fi
	setup-util "${options[@]}" || return

	# configure
	__reconfigure || return
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_starship "$@"
fi
