#!/usr/bin/env bash

# https://github.com/ClementTsang/bottom
# top alternative
# Fixed for Arch: use PACMAN='bottom' (available in extra repo)

function setup_util_bottom() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	if setup-util --check --cli=btm "$@"; then
		return 0
	fi

	# setup
	local arch options=(
		--name='bottom'
		--cli='btm'
		"$@"
		PACMAN='bottom'              # ARCH (extra repo)
		AUR='bottom-bin'             # ARCH AUR fallback
		BREW='bottom'
		CARGO='bottom'
		DNF_COPR='atim/bottom'
		DNF='bottom'                 # FEDORA
		EMERGE='sys-process/bottom'  # GENTOO
		EOPKG='bottom'               # SOLUS
		NIX='bottom'
		PORT='bottom'
		SCOOP='bottom'
		WINGET='bottom'
	)
	arch="$(get-arch)"
	function __get_github_asset_url {
		local regexp
		regexp="$(echo-escape-regexp -- "$1")$" || return
		github-download --dry --slug='ClementTsang/bottom' --latest --asset-regexp="$regexp" | echo-first-line || return
	}
	function __add_download_option {
		local url
		url="$(__get_github_asset_url "$1")" || return
		options+=(
			DOWNLOAD="$url"
			DOWNLOAD_ARCHIVE_GLOB='btm'
		)
	}
	if is-mac; then
		__add_download_option '_x86_64-apple-darwin.tar.gz' || :
	elif is-linux; then
		if [[ $arch == 'a64' ]]; then
			__add_download_option '_aarch64-unknown-linux-gnu.tar.gz' || :
		elif [[ $arch == 'a32' ]]; then
			__add_download_option '_armv7-unknown-linux-gnu.tar.gz' || :
		elif [[ $arch == 'x64' ]]; then
			__add_download_option '_x86_64-unknown-linux-musl.tar.gz' || :
		elif [[ $arch == 'x32' ]]; then
			__add_download_option '_i686-unknown-linux-musl.tar.gz' || :
		elif [[ $arch == 'r64' ]]; then
			__add_download_option '_riscv64gc-unknown-linux-gnu.tar.gz' || :
		fi
	fi
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_bottom "$@"
fi
