#!/usr/bin/env bash

function setup_util_nu_local() (
	source "$DOROTHY/sources/bash.bash"

	# options
	local state_path="$DOROTHY/state"
	local nu_state_path="$state_path/nushell"

	# nushell requires all sources files to exist ahead of time
	function __quoted_realpath {
		local path="$1"
		path="$(fs-path --resolve -- "$path")" || return $?
		echo-quote -- "$path" || return $?
	}

	function __write_state_config {
		local file="$1" content="$2"
		if [[ -n $content ]]; then
			__print_lines '#!/usr/bin/env nu' "$content" >"$file" || return $?
		else
			__print_lines '#!/usr/bin/env nu' >"$file" || return $?
		fi
	}

	# if reconfigure is not desired, or if not installed, then don't reconfigure
	if __command_missing -- nu; then
		return 0
	fi

	# prep
	fs-mkdir "$nu_state_path" || return $?

	if [[ -d "$DOROTHY/user/custom" ]]; then
		for source_file in "$DOROTHY/user/custom"/*.nu; do
			if [[ -f "$source_file" ]]; then
				local basename
				basename="$(basename "$source_file")"
				__write_state_config "$nu_state_path/$basename" "source $(__quoted_realpath "$source_file")" || return $?
			fi
		done
	fi

	# finish
	$DOROTHY/commands/setup-util-nu
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_nu_local "$@"
fi
