#!/usr/bin/env bash

# https://github.com/obsproject/obs-studio/releases
# Fixed for Arch: added PACMAN/FLATPAK options

function setup_util_obs() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	if setup-util "$@" --check --app='OBS'; then
		return 0
	fi

	# determine options
	local arch options=(
		--name='Open Broadcaster Software'
		--app='OBS'
		"$@"
		CASK='obs'
		PACMAN='obs-studio'          # ARCH (extra repo)
		FLATPAK='com.obsproject.Studio'
		WINGET='XPFFH613W8V6LV'      # Microsoft Store
	)
	function __get_github_asset_url {
		local regexp
		regexp="$(echo-escape-regexp -- "$1")$" || return
		github-download --dry --slug='obsproject/obs-studio' --latest --asset-regexp="$regexp" | echo-first-line || return
	}
	function __add_download_app_option {
		local url
		url="$(__get_github_asset_url "$1")" || return
		options+=(
			DOWNLOAD="$url"
			DOWNLOAD_ARCHIVE_GLOB='*/OBS.app'
			DOWNLOAD_FILENAME='OBS.app'
		)
	}
	function __add_deb_option {
		local url
		url="$(__get_github_asset_url "$1")" || return
		options+=(
			DEB="$url"
		)
	}
	arch="$(get-arch)"
	if is-mac; then
		if [[ $arch == 'a64' ]]; then
			__add_download_app_option '-macOS-Apple.dmg' || :
		elif [[ $arch == 'x64' ]]; then
			__add_download_app_option '-macOS-Intel.dmg' || :
		fi
	elif [[ $arch == 'x64' ]] && is-ubuntu; then
		__add_deb_option ".$(get-ubuntu-release-name)_amd64.deb" || :
	fi
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_obs "$@"
fi
