[tools]
# === Runtimes ===
node = "22"
pnpm = "latest"
bun = "latest"
deno = "latest"
python = "3.12"
go = "latest"
rust = "latest"
"npm:varlock" = "latest"
shellcheck = "latest"
packer = "latest"

[settings]
experimental = true
