[tools]
# === Runtimes ===
node = "24"
pnpm = "latest"
bun = "latest"
deno = "latest"
python = "3.12"
go = "latest"
rust = "latest"
"npm:varlock" = "latest"
shellcheck = "latest"
packer = "latest"
osv-scanner = "latest"
usage = "latest"
"github:can1357/oh-my-pi" = "16.1.10"
"pipx:hindsight-api" = "latest"
supabase = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:pyright" = "latest"
"github:bee-san/rustscan" = "latest"
"github:cai0baa/cmux-for-linux" = "latest"
hugo-extended = "latest"

[settings]
experimental = true

[settings.python]
default_packages_file = "~/.config/dorothy/config/default-python-packages"
